Fix string substitution in check_rabbitmq_cluster
The string substitution in the check_rabbitmq_cluster script was
improperly configured outside of the print statement. As a result, users
did not receive alerts when a RabbitMQ cluster went down and encountered
TypeError: unsupported operand when executing the script.

Closes-bug: #2080883

Change-Id: I049146cbd029e809bfc500a98fd62fff24ebda95
(cherry picked from commit 0914109091bcd8850ef39c4f2235d5dfd548cc88)